// Test generated by Testify

import { formatTimestamp } from './utils';

describe('formatTimestamp function', () => {
  it('should format timestamp correctly', () => {
    const timestamp = '2022-01-01T12:00:00';
    const expected = '01 January, 2022';
    expect(formatTimestamp(timestamp)).toBe(expected);
  });

  it('should handle edge case with timestamp at start of day', () => {
    const timestamp = '2022-01-01T00:00:00';
    const expected = '01 January, 2022';
    expect(formatTimestamp(timestamp)).toBe(expected);
  });

  it('should handle edge case with timestamp at end of day', () => {
    const timestamp = '2022-01-01T23:59:59';
    const expected = '01 January, 2022';
    expect(formatTimestamp(timestamp)).toBe(expected);
  });

  it('should handle invalid timestamp', () => {
    const timestamp = 'invalid-timestamp';
    expect(() => formatTimestamp(timestamp)).toThrow("invalid timestamp");
  });

  it('should handle timestamp with missing time component', () => {
    const timestamp = '2022-01-01';
    const expected = '01 January, 2022';
    expect(formatTimestamp(timestamp)).toBe(expected);
  });

  it('should handle timestamp with extra characters', () => {
    const timestamp = '2022-01-01T12:00:00Z';
    const expected = '01 January, 2022';
    expect(formatTimestamp(timestamp)).toBe(expected);
  });
});